### PR TITLE
Ported @tdraier to latest version of graphql-java-servlet and added supporting tests

### PR DESCRIPTION
**Pull request by wleroux**

### CODE REVIEW

**Comment by wleroux** [comment]
While I've added tests to validate this, I have not manually tested it using an actual server.

The reason I want SSE is for security reasons. WebSockets are surprisingly difficult to get working with existing infrastructure (i.e.: CSRF/CORS) and skip all of the request filters that sets up the Authentication. With SSE, this is all free (since we're using HTTP.)

There's a couple contentious points I'd like to investigate further as well. While this should work as-is when asyncServletModeEnabled = false, I believe that the subscriptions would be prematurely completed when asyncServletModeEnabled = true as the code executes asyncContext.completed() on the finally clause in AbstractGraphQLHttpServlet#doRequest.

Anyhow, I thought I'd put this up for now. Will manually test + inspect the aforementioned issue tomorrow.

**Comment by wleroux** [comment]
It works! Manually tested this using my application. In my situation, I needed to verify that it works with CSRF-TOKEN, CORS, Authentication as well (the reason I looked into SSE in the first place.)

Additional notes: SSE only supports GET method. POST is not natively supported by `EventSource`. Some people may prefer a custom POST approach to prevent authentication information to leak into logs.

Here's an example of usage:

# Spring Boot Controller
```kotlin
@Component
class EchoController: GraphQLSubscriptionResolver {
    fun echo(arg: String): Publisher<String> {
        return Mono.just(arg)
    }
}
```

# Schema Definition
```graphql
type Subscription {
    echo(arg: String!): String!
}
```

# JavaScript Client
```javascript
import gql from "graphql-tag";

var subscriptionQuery = gql`subscription {
    echo(arg: "Hello, World!")
}`;

var eventSource = new EventSource("/graphql?query=" + encodeURIComponent(subscriptionQuery.loc.source.body));
eventSource.onmessage = message => console.log(JSON.parse(message.data).data.echo);
```

**Comment by wleroux** [comment]
I've added the configuration for the timeout of the subscription as any value is arbitrary; the previous setting of 1 minute was too short for me. The default value (0) will allow the subscription to live indefinitely... But if that's not desirable, it can be overridden.

The `asyncModeEnabled=true` did cause problems with subscriptions; the latest commit fixes that issue.

**Comment by wleroux** [comment]
@oliemansm Any hope on this making it in?

**Comment by oliemansm** [comment]
@wleroux Thanks a lot for this!!

**Pull request merged**
