### PR TITLE
javax.servlet -> jakarta.servlet:6.0

### PR DESCRIPTION
**Pull request by eduarddrenth**
updated dependencies to jakarta
updated groovy accordingly
renamed javax to jakarta

### CODE REVIEW

**Comment by eduarddrenth** [comment]
tested this PR on one of my applications, runs fine on payara 6.2022.1 / ee 10

**Comment by eduarddrenth** [comment]
fixes #484

**Comment by eduarddrenth** [comment]
build pipeline needs to support class version 55, run jdk 11

**Comment by oliemansm** [comment]
@eduarddrenth That would mean that from this version on Java 8 would no longer be supported by this library. MIght be a good moment as any to do it.

**Comment by eduarddrenth** [comment]
A metter of changing gradle.properties?
```
SOURCE_COMPATIBILITY=1.8
TARGET_COMPATIBILITY=1.8
```
to
```
SOURCE_COMPATIBILITY=11
TARGET_COMPATIBILITY=11
```

**Comment by eduarddrenth** [comment]
can you perhaps approve, so I can verify the tests succeed with my last commits?

**Comment by eduarddrenth** [comment]
I don't know how to fix the test run issues, servlet runs fine on payara 6. Perhaps lower servlet spec for better compatibility?

**Comment by eduarddrenth** [comment]
solution might be:

- use springframework 6.0.2 in unit testing
- add gradle config to run tests with java 17 (required by springframework 6)

Or redesign the test env (large impact I suspect) or skip tests (undesirable)

**Comment by oliemansm** [comment]
@eduarddrenth Since this has quite significant impact I've started a poll for this to get some insights. If the poll does not provide a clear direction or doesn't have that many votes I'll make a decision. See https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions/487

**Comment by eduarddrenth** [comment]
> @eduarddrenth Since this has quite significant impact I've started a poll for this to get some insights. If the poll does not provide a clear direction or doesn't have that many votes I'll make a decision. See #487

good idea! voted for 17 myself

**Comment by oliemansm** [comment]
@eduarddrenth Can you update your PR with the changes you've confirmed work locally? Can you sync in my latest push to master as well? That should update the github actions to work with jdk 17 only.

**Comment by eduarddrenth** [comment]
fixed some tests

**Comment by eduarddrenth** [comment]
Great!

**Pull request closed without merging**
