### PR TITLE
Moved injection of Batch handler from the servlet into query invoker

### PR DESCRIPTION
**Pull request by jmccaull**
After refactoring to allow full customization of the logic within the query invoker, I probably should have moved where the logic was injected. This ends up being much cleaner and simpler overall. Sorry, it became much more apparent when trying to utilize this in our project.

### CODE REVIEW

**Comment by jmccaull** [comment]
@oliemansm, this also removes those nulls

**Comment by oliemansm** [comment]
@jmccaull Syncing 7.3.1 to central now

**Comment by jmccaull** [comment]
@oliemansm, thanks. I see the release here but it isn't showing up on central yet, figured after 7 hrs it should be there by now. Any ideas?

**Comment by oliemansm** [comment]
@jmccaull Apparently an error occurred while syncing to Central, now it succeeded.

**Pull request merged**
