### PR TITLE
Relaxed Jakarta Servlet API version to 5.x in GraphQL Java Servlet

### PR DESCRIPTION
**Pull request by ideas-into-software**
As per Federico Rispo's comment Federico Rispo's comment (https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions/508#discussioncomment-5276382), `GraphQL Java Servlet` is dependent on `Jakarta Servlet 6.x` only because of `Spring` dependencies, which are only used for testing. Therefore, it was possible to relax `Jakarta Servlet API` version to `5.x`, while keeping `Jakarta Servlet API` version at `6.x` for 'testImplementation' dependencies.

Most of our projects use `Apache Felix Jetty` and requiring `Jakarta Servlet 6.x` made it impossible to use that container. 

Thanks to this small change, `GraphQL Java Servlet` is now compatible with latest version of `Apache Felix Jetty`, as well as many other servlet containers which do not yet support `Jakarta Servlet 6.x`.

### CODE REVIEW

**Comment by ideas-into-software** [comment]
Possibly a separate branch, `jakarta-servlet-5-x` could be maintained, instead of merging to master?

**Comment by juergen-albert** [comment]
Is there any interesst in merging this, as we would highly appreciate this change as well.

**Comment by federicorispo** [comment]
@ideas-into-software We created the `jakarta5` branch. Can you resolve the conflicts and point the PR to the `jakarta5` branch?

**Comment by ideas-into-software** [comment]
Closing this as @federicorispo added this to https://github.com/graphql-java-kickstart/graphql-java-servlet/tree/jakarta5 branch via https://github.com/graphql-java-kickstart/graphql-java-servlet/commit/72fba8be2cb945eb38303efbfd1fa7c9ff996972 commit

**Pull request closed without merging**
