### PR TITLE
`graphql-java` version 22 compatibility

### PR DESCRIPTION
**Pull request by hiddewie**
This PR makes the project compatible with GraphQL Java version 22

Changes:
- Depend on `com.graphql-java:graphql-java` version 22
- Remove everything `DataLoaderDispatcherInstrumentation` related
- Add valid locations in a test setup.

Ref https://github.com/graphql-java/graphql-java/pull/3447, which has most impact on this pull request.

### CODE REVIEW

**Comment by federicorispo** [comment]
@hiddewie Thank you very much for your time and effort on this PR. The alignment to `graphql-java:22.1` looks good. I manually tested it on my personal project and it is working as expected. 

Before merging it, I would like to remove the unused methods in the DataLoaderDispatchingSpec.groovy test class:
- [120-123](https://github.com/hiddewie/graphql-java-servlet/blob/466dbc57a3479b0cdc47388be4d82ab83ca02f0e/graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/DataLoaderDispatchingSpec.groovy#L120)
- [177-191](https://github.com/hiddewie/graphql-java-servlet/blob/466dbc57a3479b0cdc47388be4d82ab83ca02f0e/graphql-java-servlet/src/test/groovy/graphql/kickstart/servlet/DataLoaderDispatchingSpec.groovy#L177)

**Comment by hiddewie** [comment]
@federicorispo Thanks for the review!

I removed the dead code :)

**Review by federicorispo — APPROVED** [review]
Thanks for this delicate verison bump :rocket:

**Comment by hiddewie** [comment]
Perfect, thank you!

**Comment by hiddewie** [comment]
Hi @federicorispo, did you manage to release a new version so I can update all my projects using normal versions instead of snapshot versions? I don't see it listed in https://github.com/graphql-java-kickstart/graphql-java-servlet/releases. Thanks!

**Comment by hiddewie** [comment]
Thanks a lot!

**Pull request merged**
